---
grails:
    profile: web
    codegen:
        defaultPackage: hanuman.team
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false


dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect : org.hibernate.dialect.MySQL5InnoDBDialect
    username: developer
    password: 'P@ssw0rd'
    logSql: false

environments:
    development:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://192.168.1.10:3306/dev_avacass?useUnicode=yes&characterEncoding=UTF-8
#            url: jdbc:mysql://172.30.30.23/avc?useUnicode=yes&characterEncoding=UTF-8
    test:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://127.0.0.1:3306/staging_avacass?useUnicode=yes&characterEncoding=UTF-8
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

    production:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://127.0.0.1:3306/staging_avacass?useUnicode=yes&characterEncoding=UTF-8
#            password: 'Online@!##S123'
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
#--- redis
---
grails:
    redis:
        port: 6379
        database: 2
        timeout: 2000
        poolConfig:
            testWhileIdle: true
            maxTotal: 500
environments:
    development:
        grails:
            redis:
                host: "192.168.1.10"
                password: P@ssw0rd
    test:
        grails:
            redis:
                host: "127.0.0.1"
                password: V5-yyWDUG7=B[
    production:
        grails:
            redis:
                host: "127.0.0.1"
                password: V5-yyWDUG7=B[
---
grails:
    plugin:
        awssdk:
            accessKey: ODSIMOJTKQM24LXMNTDV
            secretKey: /vpmYb0E0kcQvOFi9xJ8CDyPEB69bNHLEjAGPc7MtsM
            endpoint: sgp1.digitaloceanspaces.com
            region: sgp1
            s3:
                bucket: avaccas
---
grails:
    cors:
        enabled: true
